language: go
go:
  - "stable"

# Install OS dependencies to support video/audio output
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgl1-mesa-dev and xorg-dev portaudio19-dev

script:
  - go test ./...
